name: Terraform Apply
on: workflow_dispatch
#env:
#

jobs:
  Terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init
    


    - name: Terraform Apply
      run: terraform apply -auto-approve
