name: Terraform Plan
on: push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  Terraform:
    name: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform Init
    
    - name: Terraform Validate
      run: terraform Validate

    - name: Terraform Plan
      run: terraform plan
